### ISSUE TITLE
Can't compile assets under Rails 3.2.9.rc1

### ISSUE THREAD

**Issue by pivotal-chorus** [ndbroadbent/turbo-sprockets-rails3#26]
We get an error:
undefined method `compile_path?' for #Sprockets::StaticCompiler:0x2eb09b70

It looks like rails/actionpack/lib/sprockets/static_compiler.rb no longer defines a compile_path? method.

**Comment by ndbroadbent** [comment]
Right, Rails 3.2.9 has changed a few things in sprockets. I'll fix this
ASAP. Thanks for the report!

**Comment by ndbroadbent** [comment]
I've started a new minor version number at `0.3.0` to support `3.2.9.rc1` and higher. Thanks!

**Comment by clutchtutoring** [comment]
I'm getting the same issue. Using:

ruby '1.9.3'
gem 'rails', '3.2.12'
gem 'asset_sync'
gem 'turbo-sprockets-rails3', '0.2.6' (I had to put it down to this because of railties dependencies) 

Every time I deploy now I get this error: 
    Preparing app for Rails asset pipeline
    Running: rake assets:precompile
    AssetSync: using /tmp/build_br8mhk0oq3q4/config/initializers/asset_sync.rb
    rake aborted!
    undefined method `compile_path?' for #Sprockets::StaticCompiler:0x00000004f91a88

I had the turbo sprockets version above 0.3.0 for a while and I think it was never working (since it took a long time each time precompiling). I put it down to 0.2.6 since I'm using Rails 3.2.12, but it's now giving me that trouble. 

Not sure what to do to be honest. Any help would be appreciated!

**Comment by nfriend21** [comment]
+1
