### ISSUE TITLE
Compatibility with asset_sync gem

### ISSUE THREAD

**Issue by steverandy** [ndbroadbent/turbo-sprockets-rails3#4]
Is this gem compatible with asset_sync gem?

**Comment by ndbroadbent** [comment]
Hi there, from what I can tell, this gem runs after assets:precompile so
they should work fine together.
For now, make sure you set AssetSync.config.manifest = false, because this
gem alters the manifest format. I'll open a pull request to fix that,
though.

On 3/10/2012, at 4:13 AM, Steve Randy Tantra notifications@github.com
wrote:

Is this gem compatible with asset_sync gem?

—
Reply to this email directly or view it on
GitHubhttps://github.com/ndbroadbent/turbo-sprockets-rails3/issues/4.

**Comment by ndbroadbent** [comment]
Pull request opened on asset_sync: https://github.com/rumblelabs/asset_sync/pull/110

Compatibility notes added to README: https://github.com/ndbroadbent/turbo-sprockets-rails3#compatibility

Thanks for raising the question!
