### ISSUE TITLE
What is difference between using the buildpack and just using the gem with asset_sync?

### ISSUE THREAD

**Issue by dfuentes77** [ndbroadbent/turbo-sprockets-rails3#63]
Do you need to do both?

**Comment by dfuentes77** [comment]
I guess the questions is, do you need the buildpack if you are using asset_sync gem on heroku?

**Comment by PikachuEXE** [comment]
I guess asset sync just upload changed assets
But it does not prevent recompilation?

**Comment by ndbroadbent** [comment]
Hi there,

You do need the buildpack if you want to use turbo-sprockets-rails3 on heroku. Otherwise the gem will do nothing to speed up your asset compilation. The buildpack keeps your assets in a shared directory, so that subsequent deploys don't need to recompile assets. Otherwise, the default behaviour on Heroku is to start with an empty public/assets directory.
