### ISSUE TITLE
New css files added to a directory imported via a wildcard do not trigger a re-compile

### ISSUE THREAD

**Issue by mikegee0101** [ndbroadbent/turbo-sprockets-rails3#72]
We're seeing an issue where new css files added to a directory that we are importing via a wildcard within application.css.scss, do not trigger a re-compile.

@import "modules/*.scss";

The workaround is to open application.css.scss, dirty it, and save. This forces it to re-import the directory. Is this expected behavior, or should it detect new files within those directories? FWIW, we have no issues changing existing files within the imported directory and seeing the reflected changes.

**Comment by ndbroadbent** [comment]
Hi there, I'm aware of the issue, but unfortunately this is a pretty tough problem to solve, and I don't have any free time to work on it at the moment. The fix would involve some further overrides of the Sass gem, to utilize their import directives instead of relying on my half-baked implementation.

Sorry for the bad news, but I won't have time to fix this in the near future.

**Comment by mikegee0101** [comment]
@ndbroadbent Ok, no problem. It's certainly not critical. Thx!
